from typing import Final


MOUNTLY_SUBSCRIPTION_LENGTH = 30
TEXT_MESSAGE_INTERVAL: Final[int] = 1
SUBSCRIBE_DISCOUNT: Final[float] = 0.5
CURRENCY: Final[str] = "XTR"

MIN_WAITING_TIME_SERVICE: Final[int] = 60
MAX_WAITING_TIME_SERVICE: Final[int] = 180
MIN_WAITING_TIME_PREDICTION: Final[int] = 10
MAX_WAITING_TIME_PREDICTION: Final[int] = 15
